// Package compress provides zstd helpers used by lfs-zstd-filter.
package compress

import (
	"io"

	"github.com/klauspost/compress/zstd"
)

// LFSZMagic is a 12-byte zstd skippable frame containing "LFSZ".
// It is prepended to streams generated by this filter so we can distinguish
// them from user `.zst` files stored before the filter was enabled.
// Bytes: 0x50 0x2A 0x4D 0x18 (magic), 0x04 0x00 0x00 0x00 (size 4), L F S Z (payload)
var LFSZMagic = [12]byte{0x50, 0x2A, 0x4D, 0x18, 0x04, 0x00, 0x00, 0x00, 'L', 'F', 'S', 'Z'}

// IsLFSZstd reports whether peek begins with our custom LFSZ skippable frame.
// At least 12 bytes are required; fewer returns false.
func IsLFSZstd(peek []byte) bool {
	if len(peek) < 12 {
		return false
	}
	for i, b := range LFSZMagic {
		if peek[i] != b {
			return false
		}
	}
	return true
}

// Compress writes our skippable frame to dst, then reads src and
// writes a zstd-compressed stream. The encoder is closed before returning.
func Compress(dst io.Writer, src io.Reader) error {
	// Prepend the skippable LFSZ frame.
	if _, err := dst.Write(LFSZMagic[:]); err != nil {
		return err
	}

	enc, err := zstd.NewWriter(dst, zstd.WithEncoderLevel(zstd.SpeedDefault))
	if err != nil {
		return err
	}
	if _, err = io.Copy(enc, src); err != nil {
		enc.Close() //nolint:errcheck – returning the copy error is more useful
		return err
	}
	return enc.Close()
}

// Decompress reads a zstd stream from src and writes the original bytes to dst.
func Decompress(dst io.Writer, src io.Reader) error {
	dec, err := zstd.NewReader(src)
	if err != nil {
		return err
	}
	defer dec.Close()
	_, err = io.Copy(dst, dec)
	return err
}
